# Generated by Django 5.0 on 2024-09-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/default_profile.webp', null=True, upload_to='profile_photos'),
        ),
    ]
