# Generated by Django 5.0 on 2024-09-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_name_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
