# Generated by Django 5.0 on 2024-09-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rating_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
